# deployment pipline for demand front end code

image: atlassian/default-image:2

pipelines:
  branches:
   test-deployment:
    - step:
       name: Deploy
       deployment: Test
       script:
         - pipe: atlassian/ssh-run:0.2.2
           variables:
             SSH_USER: $USER
             SERVER: $DEMAND_SERVER
             COMMAND: './deploy-demand-fe.sh'