# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPlaceOrder():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def login(self):
    self.driver.get("https://demand.team21.sweispring21.tk/")
    self.driver.set_window_size(1280, 720)
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(4)").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("larryboy@vt.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("sillys0NGSwM3!")
    self.driver.find_element(By.ID, "submitLogin").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
  
  def test_placeOrder(self):
    self.Login()
    self.driver.find_element(By.LINK_TEXT, "My Dashboard").click()
    self.driver.find_element(By.ID, "rideShare").click()
    self.driver.find_element(By.ID, "street_address").click()
    self.driver.find_element(By.ID, "street_address").send_keys("520 Woodward St, Apartment 1415")
    self.driver.find_element(By.ID, "city").send_keys("Austin")
    self.driver.find_element(By.ID, "state").send_keys("TX")
    self.driver.find_element(By.ID, "zip_code").send_keys("78704")
    self.driver.find_element(By.ID, "cc_name").click()
    self.driver.find_element(By.ID, "cc_name").send_keys("Larry")
    self.driver.find_element(By.ID, "cc_number").click()
    self.driver.find_element(By.ID, "cc_number").send_keys("1234123412341234")
    self.driver.find_element(By.ID, "exp_date").click()
    self.driver.find_element(By.ID, "exp_date").send_keys("05/23")
    self.driver.find_element(By.ID, "cvv").click()
    self.driver.find_element(By.ID, "cvv").send_keys("123")
    self.driver.find_element(By.ID, "submitRequest").click()
    self.driver.find_element(By.LINK_TEXT, "Click here to return to your dashboard").click()
    self.Logout()
  
